-- Enable UUID extension for generating IDs
create extension if not exists "uuid-ossp";

-- 1. Create Accounts Table
create table public.accounts (
  id uuid default uuid_generate_v4() primary key,
  username text unique not null,
  password text not null, -- Note: In a production app, use Supabase Auth or hash passwords!
  position text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Registered Accounts
insert into public.accounts (username, password, position)
values
  ('ILatteralus', 'Cfo1239', 'CFO'),
  ('BALLs321', 'ceo1239', 'CEO');

-- 2. Create Categories Table
create table public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  type text not null, -- 'Revenue' or 'Expense'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Default Categories
insert into public.categories (name, type)
values
  -- Revenue
  ('Sales Revenue', 'Revenue'),
  ('Contract Revenue', 'Revenue'),
  ('Investment', 'Revenue'),
  ('Miscellaneous', 'Revenue'),
  -- Expense
  ('Hops', 'Expense'),
  ('Malt', 'Expense'),
  ('Barley', 'Expense'),
  ('Yeast', 'Expense'),
  ('Bottles', 'Expense'),
  ('Barrels', 'Expense'),
  ('Payroll', 'Expense'),
  ('Rent', 'Expense'),
  ('Utilities', 'Expense'),
  ('Equipment', 'Expense'),
  ('Tax', 'Expense');

-- 3. Create Transactions Table
create table public.transactions (
  id bigint generated by default as identity primary key,
  date date not null,
  type text not null check (type in ('Credit', 'Debit')),
  category text references public.categories(name), -- Optional FK, or just text
  amount numeric(10, 2) not null,
  memo text,
  submitted_by text,
  status text default 'Pending',
  approved_by text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Create Inventory Table (Empty for now)
create table public.inventory (
  id bigint generated by default as identity primary key,
  item_name text unique not null,
  quantity integer default 0,
  est_value numeric(10, 2) default 0,
  last_updated timestamp with time zone default timezone('utc'::text, now())
);
